"use client";

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { BookOpenIcon, SpeakerWaveIcon, ChevronLeftIcon, ChevronRightIcon } from '@/components/icons';
import { useAppContext } from '@/context/AppContext';
import curriculumData from '@/curriculum_content.json';
import type { CurrentLesson } from '@/types';

type Grade = 'grade_10' | 'grade_11' | 'grade_12';
type Subject = 'mathematics' | 'science' | 'english';

interface Topic {
  topic: string;
  content: string;
}

interface SubjectData {
  grade: number;
  subject: string;
  topics: Topic[];
}

const CurriculumPage: React.FC = () => {
  const router = useRouter();
  const { setSelectedLesson, setCurrentEnrollment } = useAppContext();
  const [selectedGrade, setSelectedGrade] = useState<Grade | null>(null);
  const [selectedSubject, setSelectedSubject] = useState<Subject | null>(null);
  const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null);
  const [searchTerm, setSearchTerm] = useState('');

  const grades = [
    { key: 'grade_10', label: 'Grade 10', description: 'Foundation concepts' },
    { key: 'grade_11', label: 'Grade 11', description: 'Intermediate topics' },
    { key: 'grade_12', label: 'Grade 12', description: 'Advanced studies' }
  ];

  const subjects = [
    { key: 'mathematics', label: 'Mathematics', icon: '🔢', color: 'bg-blue-500' },
    { key: 'science', label: 'Science', icon: '🔬', color: 'bg-green-500' },
    { key: 'english', label: 'English', icon: '📚', color: 'bg-purple-500' }
  ];

  const speakText = (text: string) => {
    if ('speechSynthesis' in window) {
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = 0.9;
      utterance.lang = 'en-US';
      window.speechSynthesis.speak(utterance);
    }
  };

  const goBack = () => {
    if (selectedTopic) {
      setSelectedTopic(null);
    } else if (selectedSubject) {
      setSelectedSubject(null);
    } else if (selectedGrade) {
      setSelectedGrade(null);
    }
  };

  const getCurrentSubjectData = (): SubjectData | null => {
    if (!selectedGrade || !selectedSubject) return null;
    return curriculumData.curriculum[selectedGrade][selectedSubject];
  };

  const getFilteredTopics = (): Topic[] => {
    const subjectData = getCurrentSubjectData();
    if (!subjectData) return [];
    
    if (!searchTerm) return subjectData.topics;
    
    return subjectData.topics.filter(topic =>
      topic.topic.toLowerCase().includes(searchTerm.toLowerCase()) ||
      topic.content.toLowerCase().includes(searchTerm.toLowerCase())
    );
  };

  const getBreadcrumbs = () => {
    const crumbs = [];
    
    if (selectedGrade) {
      const grade = grades.find(g => g.key === selectedGrade);
      crumbs.push(grade?.label || '');
    }
    
    if (selectedSubject) {
      const subject = subjects.find(s => s.key === selectedSubject);
      crumbs.push(subject?.label || '');
    }
    
    if (selectedTopic) {
      crumbs.push(selectedTopic.topic);
    }
    
    return crumbs;
  };

  const handleTopicSelect = (topic: Topic) => {
    if (!selectedGrade || !selectedSubject) return;

    const subjectData = getCurrentSubjectData();
    if (!subjectData) return;

    // Create a lesson object that matches the CurrentLesson interface
    const lesson: CurrentLesson = {
      id: `${selectedGrade}_${selectedSubject}_${topic.topic.replace(/\s+/g, '_').toLowerCase()}`,
      title: subjectData.subject,
      lessons: subjectData.topics.length,
      progress: 0,
      topic: topic.topic,
      description: `${subjectData.subject} - ${topic.topic}`,
      image: `/public/${selectedSubject}1.jpeg`, // Default image
      content: {
        original: topic.content,
        simplified: topic.content, // Will be generated by AI later
        visualPrompt: `Create a visual representation of ${topic.topic} in ${subjectData.subject} for ${subjectData.grade}th grade students.`
      },
      grade: subjectData.grade,
      subjectKey: selectedSubject,
      gradeKey: selectedGrade
    };

    // Set the lesson in context
    setSelectedLesson(lesson);

    // Set current enrollment
    setCurrentEnrollment({
      grade: selectedGrade,
      subject: selectedSubject,
      topic: topic.topic
    });

    // Navigate to content page
    router.push(`/content/${lesson.id}`);
  };

  const handleStartLearning = () => {
    if (selectedTopic) {
      handleTopicSelect(selectedTopic);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="p-6 md:p-10 max-w-7xl mx-auto">
        {/* Header */}
        <div className="bg-gradient-to-r from-orange-500 to-orange-600 text-white p-8 md:p-12 rounded-2xl shadow-xl mb-8 relative overflow-hidden">
          {/* Decorative background elements */}
          <div className="absolute top-0 right-0 w-64 h-64 bg-orange-400 rounded-full opacity-20 transform translate-x-1/3 -translate-y-1/3"></div>
          <div className="absolute bottom-0 left-0 w-48 h-48 bg-orange-400 rounded-full opacity-10 transform -translate-x-1/4 translate-y-1/4"></div>
          
          <div className="relative z-10">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-4xl md:text-5xl font-bold mb-4">Curriculum Explorer</h1>
                <p className="text-xl md:text-2xl mb-8 opacity-90">
                  Discover comprehensive learning content across all grades and subjects
                </p>
              </div>
              <BookOpenIcon className="h-16 w-16 md:h-20 md:w-20 opacity-50" />
            </div>
            
            {/* Breadcrumbs */}
            {getBreadcrumbs().length > 0 && (
              <div className="flex items-center space-x-2 mt-4">
                <button
                  onClick={goBack}
                  className="flex items-center px-4 py-2 bg-orange-700 text-white rounded-full hover:bg-orange-800 transition-colors"
                >
                  <ChevronLeftIcon className="h-4 w-4 mr-2" />
                  Back
                </button>
                <div className="flex items-center space-x-2 text-orange-100">
                  {getBreadcrumbs().map((crumb, index) => (
                    <React.Fragment key={index}>
                      <span>{crumb}</span>
                      {index < getBreadcrumbs().length - 1 && (
                        <ChevronRightIcon className="h-4 w-4" />
                      )}
                    </React.Fragment>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Grade Selection */}
        {!selectedGrade && (
          <div className="mb-8">
            <h2 className="text-3xl font-bold text-gray-800 mb-6">Select Your Grade</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {grades.map(grade => (
                <button
                  key={grade.key}
                  onClick={() => setSelectedGrade(grade.key as Grade)}
                  className="bg-white rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 p-8 text-left border border-gray-100 hover:border-orange-200 group"
                >
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-2xl font-bold text-gray-800 group-hover:text-orange-600 transition-colors">
                      {grade.label}
                    </h3>
                    <div className="w-12 h-12 bg-orange-100 rounded-full flex items-center justify-center group-hover:bg-orange-200 transition-colors">
                      <span className="text-2xl font-bold text-orange-600">
                        {grade.key.split('_')[1]}
                      </span>
                    </div>
                  </div>
                  <p className="text-gray-600 group-hover:text-gray-700 transition-colors">
                    {grade.description}
                  </p>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Subject Selection */}
        {selectedGrade && !selectedSubject && (
          <div className="mb-8">
            <h2 className="text-3xl font-bold text-gray-800 mb-6">Choose a Subject</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {subjects.map(subject => (
                <button
                  key={subject.key}
                  onClick={() => setSelectedSubject(subject.key as Subject)}
                  className="bg-white rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 p-8 text-left border border-gray-100 hover:border-orange-200 group"
                >
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-2xl font-bold text-gray-800 group-hover:text-orange-600 transition-colors">
                      {subject.label}
                    </h3>
                    <div className={`w-12 h-12 ${subject.color} rounded-full flex items-center justify-center group-hover:scale-110 transition-transform`}>
                      <span className="text-2xl">{subject.icon}</span>
                    </div>
                  </div>
                  <p className="text-gray-600 group-hover:text-gray-700 transition-colors">
                    {curriculumData.curriculum[selectedGrade]?.[subject.key as Subject]?.topics?.length || 0} topics available
                  </p>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Topic Selection */}
        {selectedGrade && selectedSubject && !selectedTopic && (
          <div className="mb-8">
            <div className="flex flex-col md:flex-row items-start md:items-center justify-between mb-6 gap-4">
              <h2 className="text-3xl font-bold text-gray-800">Select a Topic</h2>
              
              {/* Search Input */}
              <div className="relative">
                <svg className="w-5 h-5 absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
                <input
                  type="text"
                  placeholder="Search topics..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10 pr-4 py-2 w-64 bg-white border border-gray-200 rounded-full focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-transparent text-gray-700 shadow-sm"
                />
              </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {getFilteredTopics().map((topic, index) => (
                <button
                  key={index}
                  onClick={() => handleTopicSelect(topic)}
                  className="bg-white rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 p-6 text-left border border-gray-100 hover:border-orange-200 group"
                >
                  <h3 className="text-xl font-bold text-gray-800 group-hover:text-orange-600 transition-colors mb-3">
                    {topic.topic}
                  </h3>
                  <p className="text-gray-600 group-hover:text-gray-700 transition-colors line-clamp-3">
                    {topic.content.substring(0, 150)}...
                  </p>
                  <div className="mt-4 pt-4 border-t border-gray-100">
                    <span className="text-orange-500 font-medium">Start Learning →</span>
                  </div>
                </button>
              ))}
            </div>
            
            {getFilteredTopics().length === 0 && (
              <div className="text-center py-12">
                <p className="text-gray-500 text-lg">No topics found matching your search.</p>
              </div>
            )}
          </div>
        )}

        {/* Topic Content */}
        {selectedTopic && (
          <div className="mb-8">
            <div className="bg-white rounded-2xl shadow-lg p-8 border border-gray-100">
              <div className="flex items-start justify-between mb-6">
                <div className="flex-1">
                  <h2 className="text-3xl font-bold text-gray-800 mb-2">{selectedTopic.topic}</h2>
                  <p className="text-gray-600 mb-4">
                    {getCurrentSubjectData()?.subject} • Grade {getCurrentSubjectData()?.grade}
                  </p>
                </div>
                <div className="flex items-center space-x-3">
                  <button
                    onClick={() => speakText(selectedTopic.content)}
                    className="flex items-center px-4 py-2 bg-gray-100 text-gray-600 rounded-full hover:bg-gray-200 transition-colors"
                  >
                    <SpeakerWaveIcon className="h-5 w-5 mr-2" />
                    <span className="font-medium">Listen</span>
                  </button>
                  <button
                    onClick={handleStartLearning}
                    className="flex items-center px-6 py-2 bg-orange-500 text-white rounded-full hover:bg-orange-600 transition-colors font-semibold"
                  >
                    <BookOpenIcon className="h-5 w-5 mr-2" />
                    Start Learning
                  </button>
                </div>
              </div>
              
              <div className="prose prose-lg max-w-none">
                <div className="text-gray-700 leading-relaxed text-lg">
                  {selectedTopic.content.split('\n').map((paragraph, idx) => (
                    <p key={idx} className="mb-4">
                      {paragraph}
                    </p>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Stats Section */}
        {!selectedGrade && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div className="bg-white rounded-2xl shadow-lg p-6 text-center border border-gray-100">
              <div className="text-4xl font-bold text-orange-600 mb-2">3</div>
              <div className="text-gray-600">Grade Levels</div>
            </div>
            <div className="bg-white rounded-2xl shadow-lg p-6 text-center border border-gray-100">
              <div className="text-4xl font-bold text-orange-600 mb-2">9</div>
              <div className="text-gray-600">Subjects</div>
            </div>
            <div className="bg-white rounded-2xl shadow-lg p-6 text-center border border-gray-100">
              <div className="text-4xl font-bold text-orange-600 mb-2">90</div>
              <div className="text-gray-600">Topics</div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default CurriculumPage; 